spring:
  profiles.active: ${APP_PROFILE:test}
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME:none}
    password: ${EMAIL_PASSWORD:none}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
default:
  sender: ${EMAIL_SENDER:none}
  recipient: ${EMAIL_RECIPIENT:none}

#jwt:
#  secret: ${JWT_SECRET:none}
#  expiration: ${JWT_EXPIRATION:86400}
#
#aws:
#  access_key_id: ${AWS_KEY:none}
#  secret_access_key: ${AWS_SECRET:none}
#s3:
#  bucket: api-spring-ionic
#  region: sa-east-1
#
#img:
#  prefix.client.profile: cp
#  profile.size: 200




