spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springcourse
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

#        GENERATE SQL
#        hbm2ddl.delimiter: ;
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#        GENERATE SQL

