spring:
  datasource:
    url: ${DATABASE_URL}
  mail:
    username: ${EMAIL_USERNAME:none}
    password: ${EMAIL_PASSWORD:none}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false