spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/courserefactor
    username: courserefactor
    password: 123456
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    properties.hibernate.format_sql: true
