spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springcourse
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

#        GENERATE SQL
#        hbm2ddl.delimiter: ;
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#        GENERATE SQL

